config/routes.rb
Nejpms::Application.routes.draw do
  resources :account_payables do
    collection do
      get :select
      post :confirm
      post :ok
      post :new2
    end
  end

  resources :storings

  resources :deliveries do
    collection do
      get :select
    end
  end

  resources :inventory_clearances do
    collection do
      get :select
    end
  end

  resources :inventory_clearance_settings

  resources :asset_list_masters, only: [:index,:show] do
    collection do
      get  :select
      post  :index
      get  :back2
    end
    member do
      get :tran_show
    end
  end

  resources :corp_locations

  resources :management_accounts

  resources :wallet_journals

  resources :market_orders

  resources :product_sales

  resources :costs

  resources :product_results do
    collection do
      get  :select
      post  :new2
    end
  end

  resources :user_lists

  resources :asset_lists do
    collection do
      post 'search'
    end
  end

  resources :blue_print_purchases

  resources :material_purchases

  resources :manufacturing_costs, only: [:index]

  resources :material_shortages, only: [:index, :show] do
    collection do
      get :select
      post:index
      post :confirm
    end
  end

  resources :inventory_transitions, only: [:index, :show]

  root :to => 'home#index'

end

app/models/wallet_journal.rb
# coding: utf-8

class WalletJournal
  include DataMapper::Resource

  storage_names[:default] = 'WalletJournal'

  property :transaction_id , Integer, field: 'transactionID', key: true, required: true
  property :transaction_date_time, DateTime, field: 'transactionDateTime'
  property :transaction_type_id, Integer, field: 'typeID'
  property :owner_name1, String, field: 'ownerName1'
  property :owner_id1, String, field: 'ownerID1'
  property :owner_name2, String, field: 'ownerName2'
  property :owner_id2, String, field: 'ownerID2'
  property :arg_name1, String, field: 'argName1'
  property :arg_id1, String, field: 'argID1'
  property :amount, Float, field: 'amount'
  property :balance, Float, field: 'balance'
  property :reason, String, field: 'Reason'
  property :tax_receiver_id, String, field: 'taxReceiverID'
  property :tax_amount, Float, field: 'taxAmount'

end

app/controllers/wallet_journals_controller.rb
class WalletJournalsController < ApplicationController
  # GET /wallet_journals
  # GET /wallet_journals.json
  def index
    @wallet_journals = WalletJournal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wallet_journals }
    end
  end

  # GET /wallet_journals/1
  # GET /wallet_journals/1.json
  def show
    @wallet_journal = WalletJournal.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wallet_journal }
    end
  end

  # GET /wallet_journals/new
  # GET /wallet_journals/new.json
  def new
    @wallet_journal = WalletJournal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wallet_journal }
    end
  end

  # GET /wallet_journals/1/edit
  def edit
    @wallet_journal = WalletJournal.get(params[:id])
  end

  # POST /wallet_journals
  # POST /wallet_journals.json
  def create
    @wallet_journal = WalletJournal.new(wallet_journal_params)

    respond_to do |format|
      if @wallet_journal.save
        format.html { redirect_to @wallet_journal, notice: 'Wallet journal was successfully created.' }
        format.json { render json: @wallet_journal, status: :created, location: @wallet_journal }
      else
        format.html { render action: "new" }
        format.json { render json: @wallet_journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallet_journals/1
  # PATCH/PUT /wallet_journals/1.json
  def update
    @wallet_journal = WalletJournal.get(params[:id])

    respond_to do |format|
      if @wallet_journal.update(wallet_journal_params)
        format.html { redirect_to @wallet_journal, notice: 'Wallet journal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wallet_journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallet_journals/1
  # DELETE /wallet_journals/1.json
  def destroy
    @wallet_journal = WalletJournal.get(params[:id])
    @wallet_journal.destroy

    respond_to do |format|
      format.html { redirect_to wallet_journals_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def wallet_journal_params
      params.require(:wallet_journal).permit(:amount, :arg_id1, :arg_name1, :balance, :owner_id1, :owner_id2, :owner_name1, :owner_name2, :reason, :tax_amount, :tax_receiver_id, :transaction_date_time, :transaction_id, :transaction_type_id)
    end
end

app/helpers/wallet_journals_helper.rb
module WalletJournalsHelper
end

app/views/wallet_journals/_form.html.erb
<%= form_for(@wallet_journal) do |f| %>
  <% if @wallet_journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wallet_journal.errors.count, "error") %> prohibited this wallet_journal from being saved:</h2>

      <ul>
      <% @wallet_journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_id %><br />
    <%= f.text_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_date_time %><br />
    <%= f.text_field :transaction_date_time %>
  </div>
  <div class="field">
    <%= f.label :transaction_type_id %><br />
    <%= f.text_field :transaction_type_id %>
  </div>
  <div class="field">
    <%= f.label :owner_name1 %><br />
    <%= f.text_field :owner_name1 %>
  </div>
  <div class="field">
    <%= f.label :owner_id1 %><br />
    <%= f.text_field :owner_id1 %>
  </div>
  <div class="field">
    <%= f.label :owner_name2 %><br />
    <%= f.text_field :owner_name2 %>
  </div>
  <div class="field">
    <%= f.label :owner_id2 %><br />
    <%= f.text_field :owner_id2 %>
  </div>
  <div class="field">
    <%= f.label :arg_name1 %><br />
    <%= f.text_field :arg_name1 %>
  </div>
  <div class="field">
    <%= f.label :arg_id1 %><br />
    <%= f.text_field :arg_id1 %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :balance %><br />
    <%= f.text_field :balance %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :tax_receiver_id %><br />
    <%= f.text_field :tax_receiver_id %>
  </div>
  <div class="field">
    <%= f.label :tax_amount %><br />
    <%= f.text_field :tax_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wallet_journals/edit.html.erb
<h1>Editing wallet_journal</h1>

<%= render 'form' %>

<%= link_to 'Show', @wallet_journal %> |
<%= link_to 'Back', wallet_journals_path %>

app/views/wallet_journals/index.html.erb
<h1>財務記録</h1>

<table id="wallet-list-table">
<thead>
  <tr>
    <th>Transaction</th>
    <th>Transaction date time</th>
    <th>Transaction type</th>
    <th>Amount</th>
    <th>Balance</th>
    <th>Owner name1</th>
    <th>Owner id1</th>
    <th>Owner name2</th>
    <th>Owner id2</th>
    <th>Arg name1</th>
    <th>Arg id1</th>
    <th>Reason</th>
    <th>Tax receiver</th>
    <th>Tax amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
<% @wallet_journals.each do |wallet_journal| %>
  <tr>
    <td><%= wallet_journal.transaction_id %></td>
    <td><%= wallet_journal.transaction_date_time %></td>
    <td><%= wallet_journal.transaction_type_id %></td>
    <td><%= wallet_journal.amount %></td>
    <td><%= wallet_journal.balance %></td>
    <td><%= wallet_journal.owner_name1 %></td>
    <td><%= wallet_journal.owner_id1 %></td>
    <td><%= wallet_journal.owner_name2 %></td>
    <td><%= wallet_journal.owner_id2 %></td>
    <td><%= wallet_journal.arg_name1 %></td>
    <td><%= wallet_journal.arg_id1 %></td>
    <td><%= wallet_journal.reason %></td>
    <td><%= wallet_journal.tax_receiver_id %></td>
    <td><%= wallet_journal.tax_amount %></td>
    <td><%= link_to 'Show', wallet_journal %></td>
    <td><%= link_to 'Edit', edit_wallet_journal_path(wallet_journal) %></td>
    <td><%= link_to 'Destroy', wallet_journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Wallet journal', new_wallet_journal_path %>

app/views/wallet_journals/new.html.erb
<h1>New wallet_journal</h1>

<%= render 'form' %>

<%= link_to 'Back', wallet_journals_path %>

app/views/wallet_journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Transaction:</b>
  <%= @wallet_journal.transaction_id %>
</p>

<p>
  <b>Transaction date time:</b>
  <%= @wallet_journal.transaction_date_time %>
</p>

<p>
  <b>Transaction type:</b>
  <%= @wallet_journal.transaction_type_id %>
</p>

<p>
  <b>Owner name1:</b>
  <%= @wallet_journal.owner_name1 %>
</p>

<p>
  <b>Owner id1:</b>
  <%= @wallet_journal.owner_id1 %>
</p>

<p>
  <b>Owner name2:</b>
  <%= @wallet_journal.owner_name2 %>
</p>

<p>
  <b>Owner id2:</b>
  <%= @wallet_journal.owner_id2 %>
</p>

<p>
  <b>Arg name1:</b>
  <%= @wallet_journal.arg_name1 %>
</p>

<p>
  <b>Arg id1:</b>
  <%= @wallet_journal.arg_id1 %>
</p>

<p>
  <b>Amount:</b>
  <%= @wallet_journal.amount %>
</p>

<p>
  <b>Balance:</b>
  <%= @wallet_journal.balance %>
</p>

<p>
  <b>Reason:</b>
  <%= @wallet_journal.reason %>
</p>

<p>
  <b>Tax receiver:</b>
  <%= @wallet_journal.tax_receiver_id %>
</p>

<p>
  <b>Tax amount:</b>
  <%= @wallet_journal.tax_amount %>
</p>


<%= link_to 'Edit', edit_wallet_journal_path(@wallet_journal) %> |
<%= link_to 'Back', wallet_journals_path %>