config/routes.rb
Nejpms::Application.routes.draw do
  resources :account_payables do
    collection do
      get :select
      post :confirm
      post :ok
      post :new2
    end
  end

  resources :storings

  resources :deliveries do
    collection do
      get :select
    end
  end

  resources :inventory_clearances do
    collection do
      get :select
    end
  end

  resources :inventory_clearance_settings

  resources :asset_list_masters, only: [:index,:show] do
    collection do
      get  :select
      post  :index
      get  :back2
    end
    member do
      get :tran_show
    end
  end

  resources :corp_locations

  resources :management_accounts

  resources :wallet_journals

  resources :market_orders

  resources :product_sales

  resources :costs

  resources :product_results do
    collection do
      get  :select
      post  :new2
    end
  end

  resources :user_lists

  resources :asset_lists do
    collection do
      post 'search'
    end
  end

  resources :blue_print_purchases

  resources :material_purchases

  resources :manufacturing_costs, only: [:index]

  resources :material_shortages, only: [:index, :show] do
    collection do
      get :select
      post:index
      post :confirm
    end
  end

  resources :inventory_transitions, only: [:index, :show]

  root :to => 'home#index'

end

app/models/cost.rb
# coding:utf-8
class Cost

  include DataMapper::Resource

  storage_names[:default] = 'Cost'

  property :type_id,Integer,field: 'typeID',key:true,required:true
  property :per_price, Float,field: 'perPrice'
  property :type, Integer,field: 'type'

  def calculate_material_cost(type_id)
    items = MaterialPurchase.all(:type_id => type_id)
    if items != nil then
      total_quantity = 0
      sum = 0
      items.map {|item|
        sum += item[:price] * item[:quantity]
        total_quantity += item[:quantity]
      }

      puts "item:"
      puts items[0][:type_id]
      puts "sum:"
      puts sum
      puts "quantity:"
      puts total_quantity

      return sum / total_quantity
    end

    return 0
  end

 def calculate_blueprint_cost(type_id)
    items = BluePrintPurchase.all(:type_id => type_id)
    if items != nil then
      total_quantity = 0
      sum = 0
      items.map {|item|
        sum += item[:price]
        total_quantity += item[:use_count]
      }

      puts "item:"
      puts items[0][:type_id]
      puts "sum:"
      puts sum
      puts "quantity:"
      puts total_quantity

      return sum / total_quantity
    end

    return 0
  end


end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @costs }
    end
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
    @cost = Cost.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/new
  # GET /costs/new.json
  def new
    @cost = Cost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/1/edit
  def edit
    @cost = Cost.get(params[:id])
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render json: @cost, status: :created, location: @cost }
      else
        format.html { render action: "new" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    @cost = Cost.get(params[:id])

    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost = Cost.get(params[:id])
    @cost.destroy

    respond_to do |format|
      format.html { redirect_to costs_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def cost_params
      params.require(:cost).permit(:per_price, :type, :type_id)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.text_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :per_price %><br />
    <%= f.text_field :per_price %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<h1>Listing costs</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Per price</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @costs.each do |cost| %>
  <tr>
    <td><%= cost.type_id %></td>
    <td><%= cost.per_price %></td>
    <td><%= cost.type %></td>
    <td><%= link_to 'Show', cost %></td>
    <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
    <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @cost.type_id %>
</p>

<p>
  <b>Per price:</b>
  <%= @cost.per_price %>
</p>

<p>
  <b>Type:</b>
  <%= @cost.type %>
</p>


<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>