config/routes.rb
Nejpms::Application.routes.draw do
  resources :account_payables do
    collection do
      get :select
      post :confirm
      post :ok
      post :new2
    end
  end

  resources :storings

  resources :deliveries do
    collection do
      get :select
    end
  end

  resources :inventory_clearances do
    collection do
      get :select
    end
  end

  resources :inventory_clearance_settings

  resources :asset_list_masters, only: [:index,:show] do
    collection do
      get  :select
      post  :index
      get  :back2
    end
    member do
      get :tran_show
    end
  end

  resources :corp_locations

  resources :management_accounts

  resources :wallet_journals

  resources :market_orders

  resources :product_sales

  resources :costs

  resources :product_results do
    collection do
      get  :select
      post  :new2
    end
  end

  resources :user_lists

  resources :asset_lists do
    collection do
      post 'search'
    end
  end

  resources :blue_print_purchases

  resources :material_purchases

  resources :manufacturing_costs, only: [:index]

  resources :material_shortages, only: [:index, :show] do
    collection do
      get :select
      post:index
      post :confirm
    end
  end

  resources :inventory_transitions, only: [:index, :show]

  root :to => 'home#index'

end

app/models/asset_list_master.rb
# coding: utf-8
class AssetListMaster
  include DataMapper::Resource

  storage_names[:default] = 'AssetListMaster'

  property :id, Serial,required:true, key:true
  property :type_id, Integer, field: 'itemID'
  property :quantity, Integer, field: 'quantity'
  property :station_id, Integer, field: 'stationID'

  belongs_to :item, 'InvTypes',
    parent_key: [:type_id],
    child_key: [:type_id]

  belongs_to :type_name_ja, 'TrnTranslations',
    parent_key: [ :key_id ],
    child_key: [ :type_id ],
    tc_id: '8',
    language_id: 'JA'

  belongs_to :description_ja, 'TrnTranslations',
    parent_key: [ :key_id ],
    child_key: [ :type_id ],
    tc_id: '33',
    language_id: 'JA'


  def get_type_name
    self.try(:item).try(:type_name)
  end

end

app/controllers/asset_list_masters_controller.rb
#coding: utf-8
class AssetListMastersController < ApplicationController
  # GET /asset_list_masters
  # GET /asset_list_masters.json
  def index

    if session[:station] == nil
      session[:station] = params[:asset_list_master][:station_id]
    end

    @station_id = session[:station]
    @station_name = StaStations.first(:station_id => @station_id)[:station_name]
    @asset_list_masters = AssetListMaster.all(:station_id => @station_id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asset_list_masters }
    end
  end

  # GET /asset_list_masters/select
  # GET /asset_list_masters/select.json
  def select
    @asset_list_masters = AssetListMaster.new
    @select_stations = CorpLocation.all
    session[:station] = nil
    respond_to do |format|
      format.html # select.html.erb
      # format.json { render json: @product_result }
    end
  end

  def back2
    redirect_to :action => 'index'

  end

  # GET /asset_list_masters/1
  # GET /asset_list_masters/1.json
  def show
    @asset_list_master = AssetListMaster.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asset_list_master }
    end
  end

  # GET /asset_list_masters/1
  # GET /asset_list_masters/1.json
  def tran_show
    @transitions = InventoryTransitions.all(:location_id => session[:station],order: :add_date.asc).all(type_id: params[:id])
    @asset = InvTypes.all(type_id: params[:id]).first
    @graph = LazyHighCharts::HighChart.new('graph') do |f|
      f.xAxis(categories: @transitions.map { |t| t.add_date.strftime("%Y/%m/%d - %H:%M:%S") })
      f.options[:chart][:defaultSeriesType] = "area"
      f.series(name: '在庫数', data: @transitions.map { |v| v.current_quantity })
    end
  end


  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def asset_list_master_params
      params.require(:asset_list_master).permit(:quantity, :type_id)
    end
end

app/helpers/asset_list_masters_helper.rb
module AssetListMastersHelper
end

app/views/asset_list_masters/_form.html.erb
<%= form_for(@asset_list_master) do |f| %>
  <% if @asset_list_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset_list_master.errors.count, "error") %> prohibited this asset_list_master from being saved:</h2>

      <ul>
      <% @asset_list_master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.text_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asset_list_masters/edit.html.erb
<h1>Editing asset_list_master</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset_list_master %> |
<%= link_to 'Back', asset_list_masters_path %>

app/views/asset_list_masters/index.html.erb
<h1>在庫マスタ</h1>

<h3> station : <%=@station_name%></h3>
<table id="asset-list-master-table">
  <thead>
    <tr>
      <th>アイテムID</th>
      <th>アイテム名(EN)</th>
      <th>アイテム名(JP)</th>
      <th>数量</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @asset_list_masters.each do |asset_list_master| %>
    <tr>
    <td><%= asset_list_master.type_id %></td>
    <td><%= asset_list_master.item.type_name %></td>
    <td><%= asset_list_master.type_name_ja.text %></td>
    <td><%= asset_list_master.quantity %></td>
    <td><%= link_to 'Show', asset_list_master %></td>
    <td><%= link_to '在庫推移', tran_show_asset_list_master_path(id:asset_list_master.type_id) %></td>
    <td><%= link_to '出庫', new_delivery_path(type_id:asset_list_master.type_id) %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

app/views/asset_list_masters/new.html.erb
<h1>New asset_list_master</h1>

<%= render 'form' %>

<%= link_to 'Back', asset_list_masters_path %>

app/views/asset_list_masters/select.html.erb
<h1>在庫マスタ</h1>
<%= form_for @asset_list_masters, url: asset_list_masters_path, method: :post do |f| %>

<div class="field">
  <%= f.label :station_id %><br />
  <%= f.collection_select :station_id,  @select_stations, :station_id, :station_name %>
</div>

<div class="actions">
  <%= f.submit("選択") %>
</div>
<% end %>

app/views/asset_list_masters/show.html.erb
<p id="notice"><%= notice %></p>

<h2>在庫詳細</h2>

<table class="table assets">
  <tbody>
    <tr>
      <th>アイテム名</th>
      <td><%= @asset_list_master.get_type_name %> ( <%= @asset_list_master.try(:item).try(:type_name_ja_text) %> )</td>
    </tr>
    <tr>
      <th>在庫</th>
      <td><%= @asset_list_master.quantity %></td>
    </tr>
    <tr>
      <th>TypeID</th>
      <td><%= @asset_list_master.type_id%></td>
    </tr>
   </tbody>
</table>


<hr/>
<h3>アイテムの詳細情報</h3>

<table class="table assets">
  <tbody>
    <tr>
      <th>基本価格</th>
      <td><%= number_with_delimiter @asset_list_master.try(:item).try(:base_price) %></td>
    </tr>
    <tr>
      <th>商品概要</th>
      <td><%= @asset_list_master.try(:item).try(:description_ja_text) %></td>
    </tr>
  </tbody>
</table>

<center>
<%= link_to back2_asset_list_masters_path(@asset_list_master),  class: 'btn' do %>
  <i class="icon-chevron-left"></i> 在庫一覧へ戻る
<% end %>
</center>

app/views/asset_list_masters/tran_show.html.erb
<p id="notice"><%= notice %></p>

<h2>在庫詳細</h2>

<table class="table assets">
  <tbody>
    <tr>
      <th>アイテム名</th>
      <td><%= @asset.type_name %> ( <%= @asset.type_name_ja_text %> )</td>
    </tr>
    <tr>
      <th>在庫</th>
      <td><%= @transitions.try(:last).try(:current_quantity) %></td>
    </tr>
  </tbody>
</table>


<hr />

<%= high_chart("sample", @graph) %>

<center>
<%= link_to back2_asset_list_masters_path(@asset_list_master),  class: 'btn' do %>
  <i class="icon-chevron-left"></i> 在庫一覧へ戻る
<% end %>
</center>

<table id="asset-list-transition-table">
  <thead>
    <tr>
      <th>日付</th>
      <th>日付(JP)</th>
      <th>推移数</th>
      <th>在庫数</th>
      <th>推移理由</th>
    </tr>
  </thead>

  <tbody>
  <% @transitions.each do |transition| %>
    <tr>
    <td><%= transition.add_date.strftime("%Y/%m/%d %H:%M:%S") %></td>
    <td><%= (transition.add_date + 9.hours).strftime("%Y/%m/%d %H:%M:%S") %></td>
    <td><%= number_with_delimiter transition.count %></td>
    <td><%= number_with_delimiter transition.current_quantity %></td>
    <td><%= transition.comment %></td>
  </tr>
<% end %>
  </tbody>
</table>