config/routes.rb
Nejpms::Application.routes.draw do
  resources :account_payables do
    collection do
      get :select
      post :confirm
      post :ok
      post :new2
    end
  end

  resources :storings

  resources :deliveries do
    collection do
      get :select
    end
  end

  resources :inventory_clearances do
    collection do
      get :select
    end
  end

  resources :inventory_clearance_settings

  resources :asset_list_masters, only: [:index,:show] do
    collection do
      get  :select
      post  :index
      get  :back2
    end
    member do
      get :tran_show
    end
  end

  resources :corp_locations

  resources :management_accounts

  resources :wallet_journals

  resources :market_orders

  resources :product_sales

  resources :costs

  resources :product_results do
    collection do
      get  :select
      post  :new2
    end
  end

  resources :user_lists

  resources :asset_lists do
    collection do
      post 'search'
    end
  end

  resources :blue_print_purchases

  resources :material_purchases

  resources :manufacturing_costs, only: [:index]

  resources :material_shortages, only: [:index, :show] do
    collection do
      get :select
      post:index
      post :confirm
    end
  end

  resources :inventory_transitions, only: [:index, :show]

  root :to => 'home#index'

end

app/models/account_payable.rb
#coding: utf-8
class AccountPayable
  include DataMapper::Resource

  storage_names[:default] = 'AccountPayable'

  property :id,Integer,required:true, key:true
  property :transaction_date_time, DateTime,field:'transactionDateTime'
  property :user_id, Integer,field:'userID'
  property :price, Integer,field:'price'
  property :status, Integer,field:'status'
  property :comment, String,field:'comment'
  property :operation_date_time, DateTime,field:'operationDateTime'

  belongs_to :status_list, 'StatusMaster',
    parent_key: [ :key_id ],
    child_key: [ :status ],
    group: 1

  belongs_to :user, 'UserList',
    parent_key: [:user_id],
    child_key:[:user_id]

  # 支払未の買掛金合計
  def get_not_pay_price_total
    total = AccountPayable.sum(:price, :conditions => ['status = ?','1'])
    total
  end

  # 支払未のユーザ別買掛金合計
  def get_not_pay_price_total_each_user(user_id)
    total = AccountPayable.sum(:price, :conditions => ['status = ? and userID = ?','1',user_id])
    total
  end

end

app/controllers/account_payables_controller.rb
#coding: utf-8
class AccountPayablesController < ApplicationController
  # GET /account_payables
  # GET /account_payables.json
  def index
    @account_payables = AccountPayable.all
    @user_list = UserList.all
    @account_payable = AccountPayable.new
    @account_payable_remain_total = AccountPayable.new.get_not_pay_price_total

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @account_payables }
    end
  end

  # GET /account_payables/1
  # GET /account_payables/1.json
  def show
    @account_payable = AccountPayable.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account_payable }
    end
  end

  def select
    @account_payable = AccountPayable.new
    respond_to do |format|
      format.html # select.html.erb
      # format.json { render json: @product_result }
    end
  end


  # GET /account_payables/new2
  # GET /account_payables/new2.json
  def new2
    user_id = params[:account_payable][:user_id]
    @account_payables = AccountPayable.all(:user_id => user_id,:status => 1) | AccountPayable.all(:user_id => user_id,:status => 3)
    @account_payable = AccountPayable.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account_payable }
    end
  end

  # GET /account_payables/1/edit
  def edit
    @account_payable = AccountPayable.get(params[:id])
  end

  def confirm
    checkbox_flags = params[:check]
    @account_payable = AccountPayable.new
    @account_payables = []
    @targets = []
    @sum = 0
    checkbox_flags.each do |check|
      target = AccountPayable.first(:id => check)
      @account_payables << target
      @targets << target[:id]
      @sum += target[:price].to_i
    end

    @targets = @targets.join(",")

    if params[:commit] == "支払い"
      @flag = "支払い"
    else
      @flag = "保留"
    end


    respond_to do |format|
      format.html # select.html.erb
      # format.json { render json: @product_result }
    end
  end


  def ok
    @account_payable = AccountPayable.new
    flag = params[:account_payable][:flag]
    checkbox_flags = params[:account_payable][:check].split(",")

    checkbox_flags.each do |check|
      target = AccountPayable.first(:id => check)

      if flag == "支払い"
        target.update(:status => 2,:operation_date_time => Time.now.utc )#utc
      else
        target.update(:status => 3,:operation_date_time => Time.now.utc )#utc
      end
    end
    respond_to do |format|
      format.html { redirect_to @account_payable, notice: 'Account payable was successfully updated.' }
      # format.json { render json: @product_result }
    end
  end

  # POST /account_payables
  # POST /account_payables.json
  def create
    @account_payable = AccountPayable.new(account_payable_params)

    respond_to do |format|
      if @account_payable.save
        format.html { redirect_to @account_payable, notice: 'Account payable was successfully created.' }
        format.json { render json: @account_payable, status: :created, location: @account_payable }
      else
        format.html { render action: "new" }
        format.json { render json: @account_payable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_payables/1
  # PATCH/PUT /account_payables/1.json
  def update
    @account_payable = AccountPayable.get(params[:id])

    respond_to do |format|
      if @account_payable.update(account_payable_params)
        format.html { redirect_to @account_payable, notice: 'Account payable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account_payable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_payables/1
  # DELETE /account_payables/1.json
  def destroy
    @account_payable = AccountPayable.get(params[:id])
    @account_payable.destroy

    respond_to do |format|
      format.html { redirect_to account_payables_url }
      format.json { head :no_content }
    end
  end

  private

  # Use this method to whitelist the permissible parameters. Example:
  # params.require(:person).permit(:name, :age)
  # Also, you can specialize this method with per-user checking of permissible attributes.
  def account_payable_params
    params.require(:account_payable).permit(:comment, :operation_date_time, :price, :status, :transaction_date_time, :user_id)
  end
end

app/helpers/account_payables_helper.rb
module AccountPayablesHelper
end

app/views/account_payables/_form.html.erb
<%= form_for(@account_payable) do |f| %>
  <% if @account_payable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_payable.errors.count, "error") %> prohibited this account_payable from being saved:</h2>

      <ul>
      <% @account_payable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_date_time %><br />
    <%= f.text_field :transaction_date_time %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :operation_date_time %><br />
    <%= f.text_field :operation_date_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/account_payables/confirm.html.erb
<h1><%= @flag %>対象確認</h1>

<table class="table assets">
  <tbody>
    <tr>
      <th>合計</th>
      <td><%= number_with_delimiter @sum %></td>
    </tr>
  </tbody>
</table>

<%= form_for @account_payable, url: ok_account_payables_path, method: :post do |f| %>
<table id="purchases-table">
  <thead>
    <tr>
      <th>取引日</th>
      <th>取引日(JP)</th>
      <th>ユーザ</th>
      <th>金額</th>
      <th>ステータス</th>
      <th>理由</th>
      <th>操作日</th>
    </tr>
  </thead>

  <tbody>
    <% @account_payables.each do |account_payable| %>
    <tr>
      <td>
        <%= account_payable.transaction_date_time.strftime("%Y/%m/%d %H:%M:%S")  %></td>
      <td>
        <%= (account_payable.transaction_date_time + 9.hours).strftime("%Y/%m/%d %H:%M:%S") %></td>
      <td>
        <%= account_payable.try(:user).try(:user_name) %></td>
      <td>
        <%= number_with_delimiter account_payable.price %></td>
      <td>
        <%= account_payable.try(:status_list).try(:key_name) %></td>
      <td>
        <%= account_payable.comment %></td>
      <td>
        <%= (account_payable.operation_date_time + 9.hours).strftime("%Y/%m/%d %H:%M:%S") %></td>
    </tr>
    <% end %></tbody>
</table>

<div class="actions">
  <%= f.hidden_field :check,:value => @targets %>
  <%= f.hidden_field :flag,:value => @flag %>
  <%= f.submit("OK") %>
  <% end %>
</div>

  <%= link_to_function "Back", "history.back()"%>

app/views/account_payables/edit.html.erb
<h1>Editing account_payable</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_payable %> |
<%= link_to 'Back', account_payables_path %>

app/views/account_payables/index.html.erb
<h1>買掛金一覧</h1>

<table class="table assets">
  <tbody>
    <tr>
      <th>買掛金残合計</th>
      <td><%= number_with_delimiter @account_payable_remain_total %></td>
    </tr>
    <% @user_list.each do |list| %>
    <tr>
      <th><%= list.user_name %> </th>
      <td><%= number_with_delimiter @account_payable.get_not_pay_price_total_each_user(list.user_id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to '支払', select_account_payables_path %>

<table id="purchases-table">
  <thead>
    <tr>
      <th>取引日</th>
      <th>取引日(JP)</th>
      <th>ユーザ</th>
      <th>金額</th>
      <th>ステータス</th>
      <th>理由</th>
      <th>操作日</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @account_payables.each do |account_payable| %>
    <tr>
    <td><%= account_payable.transaction_date_time.strftime("%Y/%m/%d %H:%M:%S")  %></td>
    <td><%= (account_payable.transaction_date_time + 9.hours).strftime("%Y/%m/%d %H:%M:%S") %></td>
    <td><%= account_payable.try(:user).try(:user_name) %></td>
    <td><%= number_with_delimiter account_payable.price %></td>
    <td><%= account_payable.try(:status_list).try(:key_name) %></td>
    <td><%= account_payable.comment %></td>
    <td><%= (account_payable.operation_date_time + 9.hours).strftime("%Y/%m/%d %H:%M:%S") %></td>
    <td><%= link_to 'Show', account_payable %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br />

app/views/account_payables/new.html.erb
<h1>New account_payable</h1>

<%= render 'form' %>

<%= link_to 'Back', account_payables_path %>

app/views/account_payables/new2.html.erb
<h1>支払い対象選択</h1>

<%= form_for @account_payable, url: confirm_account_payables_path, method: :post do |f| %>
<table id="purchases-table">
  <thead>
    <tr>
      <th></th>
      <th>取引日</th>
      <th>取引日(JP)</th>
      <th>ユーザ</th>
      <th>金額</th>
      <th>ステータス</th>
      <th>理由</th>
      <th>操作日</th>
    </tr>
  </thead>

  <tbody>
    <% @account_payables.each do |account_payable| %>
    <tr>
      <td>
        <%= check_box_tag 'check[]',account_payable.id ,false ,{}%></td>
      <td>
        <%= account_payable.transaction_date_time.strftime("%Y/%m/%d %H:%M:%S")  %></td>
      <td>
        <%= (account_payable.transaction_date_time + 9.hours).strftime("%Y/%m/%d %H:%M:%S") %></td>
      <td>
        <%= account_payable.try(:user).try(:user_name) %></td>
      <td>
        <%= number_with_delimiter account_payable.price %></td>
      <td>
        <%= account_payable.try(:status_list).try(:key_name) %></td>
      <td>
        <%= account_payable.comment %></td>
      <td>
        <%= (account_payable.operation_date_time + 9.hours).strftime("%Y/%m/%d %H:%M:%S") %></td>
    </tr>
    <% end %></tbody>
</table>

<div class="actions">
  <%= f.submit("支払い") %>
  <%= f.submit("保留") %></div>
<% end %>

<%= link_to_function "Back", "history.back()"%>

app/views/account_payables/select.html.erb
<h1>支払対象選択</h1>
<%= form_for @account_payable, url: new2_account_payables_path, method: :post do |f|%>

<div class="field">
  <%= f.label :user_id %><br />
  <%= f.collection_select :user_id,UserList.all,:user_id,:user_name %>
</div>

<div class="actions">
  <%= f.submit("選択") %>
</div>

<%= link_to_function "Back", "history.back()"%>
<% end %>

app/views/account_payables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Transaction date time:</b>
  <%= @account_payable.transaction_date_time %>
</p>

<p>
  <b>User:</b>
  <%= @account_payable.user_id %>
</p>

<p>
  <b>Price:</b>
  <%= @account_payable.price %>
</p>

<p>
  <b>Status:</b>
  <%= @account_payable.status %>
</p>

<p>
  <b>Comment:</b>
  <%= @account_payable.comment %>
</p>

<p>
  <b>Operation date time:</b>
  <%= @account_payable.operation_date_time %>
</p>


<%= link_to 'Edit', edit_account_payable_path(@account_payable) %> |
<%= link_to 'Back', account_payables_path %>